### PR TITLE
[WIP] Implementation of different initial guesses for the Newton's method

### PR DESCRIPTION
**Pull request by 20chupin**
And change `time_step` for `nb_steps`

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/14)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/14)* status: all files reviewed, 12 unresolved discussions (waiting on @20chupin)

___
*[`varint/minimal_variational_integrator.py` line 87 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe80me39jdVsJzblyj:-NVe80me39jdVsJzblyk:b-4mh9ky) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L87)):*
> ```Python
>     def __init__(
>         self,
>         biorbd_casadi_model: biorbd_casadi.Model,
> ```

I would not have change this argument
change it back to biorbd_model
___
*[`varint/minimal_variational_integrator.py` line 158 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe8P7M6Rp8Zc8rXOLz:-NVe8P7M6Rp8Zc8rXOM-:b-ncadbs) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L158)):*
> ```Python
>             or initial_guess_approximation == InitialGuessApproximation.LAGRANGIAN
>         ):
>             self.biorbd_model = biorbd.Model(biorbd_casadi_model.path().absolutePath().to_string())
> ```

load it just after
```python3
self.biorbd_model = biorbd_casadi_model
self.biorbd_numpy_model = biorbd_casadi_model
```

In any case, load it even if not used by the initial guess, we don't care that much.
___
*[`varint/minimal_variational_integrator.py` line 231 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9F2A8ET9m4Ryrq3h:-NVe9F2A8ET9m4Ryrq3i:b-1vhumm) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L231)):*
> ```Python
>         self.q0_num, self.q1_num, self.lambdas_0 = self._compute_initial_states(q_init[:, 0], q_dot_init[:, 0])
> 
>     def _compute_initial_states(self, q_init, q_dot_init):
> ```

make sure to know which type is returned
and add hints
`q_init: XXXX`...
___
*[`varint/minimal_variational_integrator.py` line 290 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9KX_AKzRaOMhsxKO:-NVe9KX_AKzRaOMhsxKP:b-7jl271) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L290)):*
> ```Python
>             return DM(q_init), DM(np.asarray(q1_opt)[:, 0]), None
> 
>     def _compute_final_velocity(self, q_penultimate, q_ultimate):
> ```

same.
___
*[`varint/minimal_variational_integrator.py` line 621 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9_ry8YDKzAD2a2Hq:-NVe9_ry8YDKzAD2a2Hr:b7amogw) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L621)):*
> ```Python
>                 )
> 
>     def _compute_initial_guess(self, q_prev, q_cur, u_cur, lambdas_num, time_step):
> ```

hints also
___
*[`varint/minimal_variational_integrator.py` line 636 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeA_zC6IA5pverH4Mk:-NVeA_zD4Dpz67UzyVpa:bljw8p8) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L636)):*
> ```Python
>             The Lagrange multipliers at the current time step.
>         time_step: int
>             The current time step.
> ```

Returns
------------
___
*[`varint/minimal_variational_integrator.py` line 638 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9mDi8Nvt7lAfWvn8:-NVe9mDi8Nvt7lAfWvn9:bqdiw5) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L638)):*
> ```Python
>             The current time step.
>         """
>         q_cur_array = np.asarray(q_cur).reshape(self.biorbd_casadi_model.nbQ())
> ```

Ok, The mix of types is very weird, but catch me when you are on it next time ! :)
I'll need to dive in it.
___
*[`varint/minimal_variational_integrator.py` line 646 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeAFQm3k6kIdaEAakc:-NVeAFQm3k6kIdaEAakd:bmluohe) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L646)):*
> ```Python
>         # The first three initial guesses are issued from https://arxiv.org/pdf/1609.02898.pdf (3.3).
>         if self.initial_guess_approximation == InitialGuessApproximation.CURRENT:
>             v_init = self._dispatch_to_v(q_cur_array, lambdas_num_array)
> ```

I would expect this function to return only, q_init as all the computation is done on q.
___
*[`varint/minimal_variational_integrator.py` line 648 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBCqE9qo2PSYzLLjQ:-NVeBCqE9qo2PSYzLLjR:b6c7leq) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L648)):*
> ```Python
>             v_init = self._dispatch_to_v(q_cur_array, lambdas_num_array)
>         elif self.initial_guess_approximation == InitialGuessApproximation.EXPLICIT_EULER:
>             v_init = self._dispatch_to_v(2 * q_cur_array - q_prev_array, lambdas_num_array)
> ```

plz compute the approximated speed separately to fits the equation in the paper and ease the reading.
___
*[`varint/minimal_variational_integrator.py` line 654 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeAiPF8vDCoHZmH-EU:-NVeAiPF8vDCoHZmH-EV:b-otc39) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L654)):*
> ```Python
>             M_inv = self.biorbd_model.massMatrixInverse(q_cur_array).to_array()
>             C = self.biorbd_model.NonLinearEffect(q_cur_array, qdot_cur_array).to_array()
>             qddot_cur = M_inv @ (-C + Q)
> ```

I should have check this, earlier.
But you can use biorbd_model.ForwardDynamics(q,qdot,u)
It does exactly the same
___
*[`varint/minimal_variational_integrator.py` line 687 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBXI6EVxNfk-qECu0:-NVeBXI6EVxNfk-qECu1:bhkiur1) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L687)):*
> ```Python
>         q_all = np.zeros((self.biorbd_casadi_model.nbQ(), self.nb_steps))
>         q_all[:, 0] = np.asarray(q_prev)[:, 0]
>         q_all[:, 1] = np.asarray(q_prev)[:, 0]
> ```

np.asarray are very weird, you need to show me why you use it.
___
*[`varint/minimal_variational_integrator.py` line 715 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBgNe9lgg8ILkw-7k:-NVeBgNe9lgg8ILkw-7l:b-8luerh) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L715)):*
> ```Python
>             except RuntimeError:
>                 print(f"The integration crashed at the {i}th time step because of the rootfinding.")
>                 break
> ```

try except make the code very slow.
you need to make this as an option for the user, if wants to use it or not.

debug_mode="on"

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/14)* status: all files reviewed, 12 unresolved discussions (waiting on @Ipuch)

___
*[`varint/minimal_variational_integrator.py` line 87 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe80me39jdVsJzblyj:-NVfToaOBr--YRt7HG65:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L87)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I would not have change this argument
change it back to biorbd_model
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 158 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe8P7M6Rp8Zc8rXOLz:-NVfTlv_3BWRDBKpIvxC:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L158)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

load it just after
```python3
self.biorbd_model = biorbd_casadi_model
self.biorbd_numpy_model = biorbd_casadi_model
```

In any case, load it even if not used by the initial guess, we don't care that much.
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 231 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9F2A8ET9m4Ryrq3h:-NVjH5GmDrka5Ef_baul:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L231)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

make sure to know which type is returned
and add hints
`q_init: XXXX`...
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 290 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9KX_AKzRaOMhsxKO:-NVjH62j31w93S1McPXs:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L290)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same.
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 621 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9_ry8YDKzAD2a2Hq:-NVjHkEO1KB1ybGV1Wpf:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L621)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

hints also
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 636 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeA_zC6IA5pverH4Mk:-NVjHkhF3zpmHkhAh59A:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L636)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Returns
------------
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 646 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeAFQm3k6kIdaEAakc:-NVfWoOZ8URzwlI8dJqt:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L646)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I would expect this function to return only, q_init as all the computation is done on q.
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 648 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBCqE9qo2PSYzLLjQ:-NVj1mPgBvUBOMxGwdPU:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L648)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

plz compute the approximated speed separately to fits the equation in the paper and ease the reading.
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 654 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeAiPF8vDCoHZmH-EU:-NVj3ztT7sUegCJ5PRZR:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L654)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I should have check this, earlier.
But you can use biorbd_model.ForwardDynamics(q,qdot,u)
It does exactly the same
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 687 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBXI6EVxNfk-qECu0:-NVjBTZKBtBoBIrRmCtW:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L687)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

np.asarray are very weird, you need to show me why you use it.
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 715 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBgNe9lgg8ILkw-7k:-NVj4bsZ9_MxLc3yMyu1:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L715)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

try except make the code very slow.
you need to make this as an option for the user, if wants to use it or not.

debug_mode="on"

</blockquote></details>

Done.

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/14)* status: all files reviewed, 7 unresolved discussions (waiting on @20chupin)

___
*[`varint/minimal_variational_integrator.py` line 621 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVe9_ry8YDKzAD2a2Hq:-NVoXT9t9nlYOzLftdbW:buwwsgp) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L621)):*
<details><summary><i>Previously, 20chupin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet :)
___
*[`varint/minimal_variational_integrator.py` line 715 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBgNe9lgg8ILkw-7k:-NVoY0ET3AG8-Y3d_put:b-udtb4c) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L715)):*
<details><summary><i>Previously, 20chupin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If out of the loop 
___
*[`varint/minimal_variational_integrator.py` line 137 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoULG242cf9Yxd893M:-NVoULG242cf9Yxd893N:birmn00) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L137)):*
> ```Python
>             The initial guess approximation used.
>         initial_guess_custom: np.ndarray | None
>             The custom initial guess custom used if initial_guess_approximation == InitialGuessApproximation.CUSTOM.
> ```

missing one docstring
___
*[`varint/minimal_variational_integrator.py` line 229 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoV8PYBMqP4Y4WrO89:-NVoV8PYBMqP4Y4WrO8A:b-4uhpj1) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L229)):*
> ```Python
>         self.q0_num, self.q1_num, self.lambdas_0 = self._compute_initial_states(q_init.squeeze(), q_dot_init.squeeze())
> 
>     def _compute_initial_states(self, q_init, q_dot_init):
> ```

q_init: type
___
*[`varint/minimal_variational_integrator.py` line 235 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoV5s-2Oi6OxzbgoBZ:-NVoV5s-2Oi6OxzbgoB_:btvwtkg) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L235)):*
> ```Python
>         Parameters
>         ----------
>         q_init: np.ndarray
> ```

DM or array finally ?
___
*[`varint/minimal_variational_integrator.py` line 304 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoXCgVCXvWJ3ZPqDyU:-NVoXCgVCXvWJ3ZPqDyV:bb7od0r) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L304)):*
> ```Python
>         return DM(q_init), q1_opt, lambdas_0_opt
> 
>     def _compute_final_velocity(self, q_penultimate, q_ultimate):
> ```

same
___
*[`varint/minimal_variational_integrator.py` line 304 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoXJbJ2bSGam9gBmBB:-NVoXJbJ2bSGam9gBmBC:b-3yrkee) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L304)):*
> ```Python
>         return DM(q_init), q1_opt, lambdas_0_opt
> 
>     def _compute_final_velocity(self, q_penultimate, q_ultimate):
> ```

-> tuple[DM, DM]
___
*[`varint/minimal_variational_integrator.py` line 317 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoXOs66EhgeuUTbINM:-NVoXOs66EhgeuUTbINN:b-816h6l) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L317)):*
> ```Python
>         Returns
>         -------
>         qN_dot: DM
> ```

Same.

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/14)* status: 26 of 27 files reviewed, 7 unresolved discussions (waiting on @Ipuch)

___
*[`varint/minimal_variational_integrator.py` line 715 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVeBgNe9lgg8ILkw-7k:-NVocbR4-nNSGCYMMDUj:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1a7948760bdcff1faae22debd9ba720fba154142/varint/minimal_variational_integrator.py#L715)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

If out of the loop 
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 137 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoULG242cf9Yxd893M:-NVo_eDU9nW6vvuMgb5D:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L137)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

missing one docstring
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 229 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoV8PYBMqP4Y4WrO89:-NVoaF-F-RP4iU1zcQY3:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L229)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

q_init: type
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 235 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoV5s-2Oi6OxzbgoBZ:-NVoaGD70nR_Xh1RsRK-:bqgn4t8) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L235)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

DM or array finally ?
</blockquote></details>

array here
___
*[`varint/minimal_variational_integrator.py` line 304 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoXCgVCXvWJ3ZPqDyU:-NVoaOFcCqC698yvVNp7:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L304)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 304 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoXJbJ2bSGam9gBmBB:-NVoaOmj0_c613e9mVea:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L304)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

-> tuple[DM, DM]
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 317 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/14#-NVoXOs66EhgeuUTbINM:-NVob8sb8M0vaUXzEPoc:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/354ca4a2a4a242b27546e496e24e4f4af4931841/varint/minimal_variational_integrator.py#L317)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.

**Review by Ipuch — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Comment by Ipuch** [comment]
LGTM!

**Pull request merged**
