### PR TITLE
Add three pendulums, correct bug w/ lambdas_all, correct the plot labels

### PR DESCRIPTION
**Pull request by 20chupin**
Add an example of a triple pendulum constructed with 3 pendulums and constraints, correct a if/else-case bug with `lambdas_all`, correct the legends of the plots for better comprehension.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/1)

### CODE REVIEW

**Review by Ipuch — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Comment by Ipuch** [comment]
Let me know when it works ? :)

**Comment by 20chupin** [comment]
How can I update a pr ? It was automatic on GitLab... Because now three_pendulums is up to date on my repo.

**Comment by Ipuch** [comment]
Each time you push, it's updated

**Comment by 20chupin** [comment]
Nice, it should be okay then

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/1)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @20chupin)

**Review by Ipuch — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/1#-:-NNDm6K89yrj28nIf_vu:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @20chupin)

**Pull request merged**
