### PR TITLE
[WIP] Correction for the controlled systems

### PR DESCRIPTION
**Pull request by 20chupin**
Rewrites the cases (forced, constrained).
Separates the examples.
Rewrites the controlled systems, addition of a new example (pendulum controlled by the response of optimal control) .
Needs to be read carefully.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/2)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
Add tests.

> Reviewed 13 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-:-NNxX2LC1XCEbdaP8vip:b-sl73in)* status: 13 of 23 files reviewed, 8 unresolved discussions (waiting on @20chupin)

___
*[`biorbd_examples/one_pendulum.py` line 3 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxT98C4ZupAJC698qx:-NNxT98C4ZupAJC698qy:b-bmav4u) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/one_pendulum.py#L3)):*
> ```Python
> """
> This script is used to integrate the motion with a variational integrator based on the discrete Lagrangian,
> and a first order quadrature method.
> ```

do this better
___
*[`biorbd_examples/one_pendulum_force.py` line 94 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTFy5BGuW2ncwGG3B:-NNxTFy5BGuW2ncwGG3C:balsewb) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/one_pendulum_force.py#L94)):*
> ```Python
>     axs[1, 1].set_title("lambda2")
> 
>     # plot total energy for both methods
> ```

put this into a function
___
*[`biorbd_examples/pendulum_control.py` line 45 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTLK76CH9qaC0RiwC:-NNxTLK76CH9qaC0RiwD:bqzehft) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/pendulum_control.py#L45)):*
> ```Python
>     print(q_vi)
> 
>     q_optimal_control = [
> ```

add a comment to tell where it comes from
___
*[`biorbd_examples/utils.py` line 108 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTTpFB4n9NiHjzV_f:-NNxTTpFB4n9NiHjzV_g:bxr0mmz) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/utils.py#L108)):*
> ```Python
>     """
>     q_middle = (q1 + q2) / 2
>     qdot_middle = (q2 - q1) / time_step
> ```

reinject quadrature rule
___
*[`varint/enums.py` line 31 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTeM0BLEoTdV-fA4k:-NNxTeM0BLEoTdV-fA4l:b2ngnxc) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/enums.py#L31)):*
> ```Python
>     """
> 
>     PIECEWISE_CONSTANT = "piecewise constant"
> ```

"_"
___
*[`varint/minimal_variational_integrator.py` line 306 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxUXyq-ZNb5Kd6zxOa:-NNxUXyq-ZNb5Kd6zxOb:b-swl7r3) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/minimal_variational_integrator.py#L306)):*
> ```Python
>         if self.constraints is not None:
>             pi_current = self.jac(q_cur)
>             return p_current + D1_Ld_qcur_qnext - transpose(pi_current) @ lambdas + self.controls_participation(control_minus, control_plus)
> ```

One line: do it outside of the if
___
*[`varint/minimal_variational_integrator.py` line 310 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxUvuk7tjg-KmZfw_K:-NNxUvuk7tjg-KmZfw_L:blnu9an) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/minimal_variational_integrator.py#L310)):*
> ```Python
>             return p_current + D1_Ld_qcur_qnext + self.controls_participation(control_minus, control_plus)
> 
>     def controls_participation(self, control_minus, control_plus):
> ```

control approximation
___
*[`varint/minimal_variational_integrator.py` line 310 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxV06LCtCl60jBiUb7:-NNxV06LCtCl60jBiUb8:bw7aotk) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/minimal_variational_integrator.py#L310)):*
> ```Python
>             return p_current + D1_Ld_qcur_qnext + self.controls_participation(control_minus, control_plus)
> 
>     def controls_participation(self, control_minus, control_plus):
> ```

add hints

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/2)* status: 9 of 25 files reviewed, 8 unresolved discussions (waiting on @Ipuch)

___
*[`biorbd_examples/one_pendulum.py` line 3 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxT98C4ZupAJC698qx:-NOGvZgA02Dt66cdKHuR:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/one_pendulum.py#L3)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

do this better
</blockquote></details>

Done.
___
*[`biorbd_examples/one_pendulum_force.py` line 94 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTFy5BGuW2ncwGG3B:-NOGwIyl1KftEhNokTve:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/one_pendulum_force.py#L94)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

put this into a function
</blockquote></details>

Done.
___
*[`biorbd_examples/pendulum_control.py` line 45 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTLK76CH9qaC0RiwC:-NOGvf-C9gbxLboYAdH-:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/pendulum_control.py#L45)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

add a comment to tell where it comes from
</blockquote></details>

Done.
___
*[`varint/enums.py` line 31 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTeM0BLEoTdV-fA4k:-NOAUnJW3TBoDsqCcnwI:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/enums.py#L31)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"_"
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 306 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxUXyq-ZNb5Kd6zxOa:-NOGvhDPEhJXDZqcSvmZ:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/minimal_variational_integrator.py#L306)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

One line: do it outside of the if
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 310 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxUvuk7tjg-KmZfw_K:-NOA_Ny96t-PfP00LE2K:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/minimal_variational_integrator.py#L310)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

control approximation
</blockquote></details>

Done.
___
*[`varint/minimal_variational_integrator.py` line 310 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxV06LCtCl60jBiUb7:-NOKik5TDfjPYdphHlyr:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/varint/minimal_variational_integrator.py#L310)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

add hints
</blockquote></details>

Done.
___
*[`biorbd_examples/utils.py` line 108 at r1](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NNxTTpFB4n9NiHjzV_f:-NOKiiP10imvmvj8v9Vu:b-896fix) ([raw file](https://github.com/Ipuch/variational_integrator/blob/1401e66e201562cd28f6c236e20da6ddfd307488/biorbd_examples/utils.py#L108)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

reinject quadrature rule
</blockquote></details>

Done.

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/2)* status: 9 of 25 files reviewed, 9 unresolved discussions (waiting on @Ipuch)

___
*[`varint/minimal_variational_integrator.py` line 360 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NOKlWSY8vps8UhIFYFA:-NOKlWSZ5Dfi6Xv9nNHD:b-cjsl38) ([raw file](https://github.com/Ipuch/variational_integrator/blob/0ec39d48c9354802bed2d167c42ef298313a7ec4/varint/minimal_variational_integrator.py#L360)):*
> ```Python
>                 )
> 
>         elif self.control_type == ControlType.PIECEWISE_CONSTANT:
> ```

Not sure at all of what is following because the function is not continuous.

**Review by Ipuch — CHANGES_REQUESTED** [review]
Okay very nice work, Almost done. We can discuss the last details this thursay.

> Reviewed 4 of 23 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-:-NOMzzEW0hksjLiQ-GBx:bkwdxb2)* status: all files reviewed, 4 unresolved discussions (waiting on @20chupin)

___
*[`varint/minimal_variational_integrator.py` line 360 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NOKlWSY8vps8UhIFYFA:-NOMz2G6-qoc2jAfy8mo:b-e1o3fj) ([raw file](https://github.com/Ipuch/variational_integrator/blob/0ec39d48c9354802bed2d167c42ef298313a7ec4/varint/minimal_variational_integrator.py#L360)):*
<details><summary><i>Previously, 20chupin wrote…</i></summary><blockquote>

Not sure at all of what is following because the function is not continuous.
</blockquote></details>

We will discuss about this tomorrow. I'm not sure either.
___
*[`varint/minimal_variational_integrator.py` line 361 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NOMzR-S1GberWP4rMFf:-NOMzR-S1GberWP4rMFg:b-rrxkg9) ([raw file](https://github.com/Ipuch/variational_integrator/blob/0ec39d48c9354802bed2d167c42ef298313a7ec4/varint/minimal_variational_integrator.py#L361)):*
> ```Python
> 
>         elif self.control_type == ControlType.PIECEWISE_CONSTANT:
>             if self.discrete_approximation == QuadratureRule.MIDPOINT or self.discrete_approximation == QuadratureRule.TRAPEZOIDAL:
> ```

Do only one if.
___
*[`varint/minimal_variational_integrator.py` line 379 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NOMzb8j1hcn--XTNbdv:-NOMzb8j1hcn--XTNbdw:b9e8ptr) ([raw file](https://github.com/Ipuch/variational_integrator/blob/0ec39d48c9354802bed2d167c42ef298313a7ec4/varint/minimal_variational_integrator.py#L379)):*
> ```Python
>             )
> 
>         return fd_minus + fd_plus
> ```

I think we should have on fonction to compute fd_minus and another one to compute fd_plus as each operation are exactly the same.
___
*[`utils.py` line 194 at r2](https://reviewable.io/reviews/Ipuch/variational_integrator/2#-NOMxrqgB9EXWd-AnpBn:-NOMxrqgB9EXWd-AnpBo:bxyjamc) ([raw file](https://github.com/Ipuch/variational_integrator/blob/0ec39d48c9354802bed2d167c42ef298313a7ec4/utils.py#L194)):*
> ```Python
>         CoM_marker = Seg * 3 + 2
>         # Rotational kinetic energy
>         I_G = biorbd_model.segments()[Seg].characteristics().inertia().to_array()
> ```

Try to avoid upper_case in python.

**Review by Ipuch — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/variational_integrator/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Pull request merged**
